[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
solc_version = "0.8.22"
remappings = ['@chainlink/contracts=lib/chainlink-brownie-contracts/contracts','@openzeppelin/contracts=lib/openzepplin-contracts/contracts']


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
